(function(g){var window=this;var hra=function(a,b){var c=[];g.Cf(b,function(a){var b;try{b=g.Ti.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.p(b)?g.Si(b)&&c.push(a):c.push(a)},a);
return c},ira=function(a,b){var c=hra(a,b);
(0,g.H)(c,function(a){g.Ti.prototype.remove.call(this,a)},a)},n9=function(a){return a.H?a.F+((0,g.G)()-a.A)/1E3:a.F},jra=function(){var a=g.Ui;
ira(a,a.g.sd(!0))},o9=function(a){g.Nz.call(this,"ScreenServiceProxy");
this.Jc=a;this.o=[];this.o.push(this.Jc.$_s("screenChange",(0,g.z)(this.EJ,this)));this.o.push(this.Jc.$_s("onlineScreenChange",(0,g.z)(this.pG,this)))},p9=function(a){g.Jz("cloudview",a)},q9=function(a){p9("setApiReady_ "+a);
g.ka("yt.mdx.remote.cloudview.apiReady_",a,void 0)},r9=function(){return g.u("yt.mdx.remote.cloudview.instance_")},s9=function(a){g.yi[a]&&(a=g.yi[a],(0,g.H)(a,function(a){g.wi[a]&&delete g.wi[a]}),a.length=0)},t9=function(){return g.u("yt.mdx.remote.connection_")},u9=function(a){g.ka("yt.mdx.remote.connectData_",a,void 0)},v9=function(a){g.ka("yt.mdx.remote.currentScreenId_",a,void 0)},w9=function(){return g.u("yt.mdx.remote.currentScreenId_")},y9=function(){if(!x9){var a=g.u("yt.mdx.remote.screenService_");
x9=a?new o9(a):null}return x9},z9=function(a){g.ka("yt.mdx.remote.cloudview.initializing_",a,void 0)},A9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},B9=function(a){p9("setCastInstalled_ "+a);
g.Wi("yt-remote-cast-installed",a)},C9=function(a){g.Jz("cloudview",a)},kra=function(a,b){r9().init(a,b)},D9=function(){return!!g.Xi("yt-remote-cast-installed")},F9=function(){p9("dispose");
var a=r9();a&&a.dispose();g.ka("yt.mdx.remote.cloudview.instance_",null,void 0);q9(!1);g.Ai(E9);E9.length=0},lra=function(){var a=window.document.createElement("a");
g.te(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Oa(a)},mra=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},nra=function(a){var b=g.ui();
if(b)if(b.clear(a),a)s9(a);else for(var c in g.yi)s9(c)},G9=function(a,b){g.xi[a]=!0;
var c=g.ui();c&&c.publish.apply(c,arguments);g.xi[a]=!1},H9=function(a){return a?a.dataset?a.dataset[g.bh("loaded")]:a.getAttribute("data-loaded"):null},I9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},K9=function(a){var b=t9();
u9(null);a||v9("");g.ka("yt.mdx.remote.connection_",a,void 0);J9&&((0,g.H)(J9,function(b){b(a)}),J9.length=0);
b&&!a?G9("yt-remote-connection-change",!1):!b&&a&&G9("yt-remote-connection-change",!0)},L9=function(){return g.u("yt.mdx.remote.connectData_")},M9=function(){var a=w9();
if(!a)return null;var b=y9().wd();return g.ei(b,a)},ora=function(a,b){B9(!0);
z9(!1);kra(a,function(a){a?(q9(!0),g.Ci("yt-remote-cast2-api-ready")):(C9("Failed to initialize cast API."),B9(!1),g.Yi("yt-remote-cast-available"),g.Yi("yt-remote-cast-receiver"),F9());b(a)})},pra=function(){return D9()?r9()?r9().getCastSession():(C9("getCastSelector: Cast is not initialized."),null):(C9("getCastSelector: Cast API is not installed!"),null)},qra=function(){if(g.fqa){var a=2,b=g.yz(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Dz("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Az,c)}},rra=function(){var a=lra(),b=window.document.getElementById(a),c=b&&H9(b);
c||b&&!c||(b=mra(a,function(){H9(b)||(g.ch(b,"loaded","true"),g.Ci(a),g.Rg(g.B(nra,a),0))}))},sra=function(a){return(0,g.R)(a,function(a){return{key:a.id,
name:a.name}})},O9=function(a,b){w9();
M9()&&M9();v9(a.id);var c=new g.YB(N9,a,I9());c.connect(b,L9());c.subscribe("beforeDisconnect",function(a){G9("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){t9()&&(t9(),K9(null))});
K9(c)},P9=function(){var a=g.aj();
if(!a)return null;var b=y9().wd();return g.ei(b,a)},Q9=function(a){g.Jz("remote",a)},R9=function(){var a=t9();
return!!a&&3!=a.getProxyState()},S9=function(){A9()?r9().stopSession():C9("stopSession called before API ready.");
var a=t9();a&&(a.disconnect(1),K9(null))},tra=function(){var a;
a=y9().Jc.$_gos();var b=M9();b&&t9()&&(g.di(a,b)||a.push(b));return sra(a)},U9=function(a,b){g.Hn.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.NB;this.A=this.o=null;this.H=(0,g.z)(this.JE,this);this.F=(0,g.z)(this.Hi,this);this.G=(0,g.z)(this.IE,this);this.J=(0,g.z)(this.SE,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.mp,this),ura(this))):c=3;0!=c&&(b?this.mp(c):g.Rg((0,g.z)(function(){this.mp(c)},this),0));
var d=pra();d&&T9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},V9=function(a){return new g.SB(a.B.getPlayerContextData())},vra=function(a,b,c,d,e){var f=V9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.WB(f,b,d);g.p(c)&&(g.UB(f,c),l.currentTime=c);g.p(k)&&(l.listId=k);W9(a,"setPlaylist",l);e||X9(a,f)},ura=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.B(this.JG,a),this))},a)},wra=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},Y9=function(a,b){50>a.C.xc()&&g.PB(a.C,b)},Z9=function(a,b,c){var d=V9(a);
g.UB(d,c);-1E3!=d.g&&(d.g=b);X9(a,d)},W9=function(a,b,c){a.B.sendMessage(b,c)},X9=function(a,b){wra(a);
a.B.setPlayerContextData(g.XB(b));ura(a)},T9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Hi(null));
a.A=b;a.A&&($9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Hi(a.A.media[0]))},xra=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=V9(a);b.contentId!=d.videoId&&$9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.UB(d,a.o.getEstimatedTime());X9(a,d)}else $9("No cast media video. Ignoring state update.")},$9=function(a){g.Jz("CP",a)},a$=function(a,b,c){return(0,g.z)(function(a){this.Qb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Qb("Retrying "+b+" using MDx browser channel."),W9(this,b,c))},a)},yra=function(a){var b=!1;
r9()||(a=new g.nA(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Wi("yt-remote-cast-available",a);G9("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){p9("onReceiverSelected: "+a.friendlyName);
g.Wi("yt-remote-cast-receiver",a);G9("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){p9("onReceiverResumed: "+a.friendlyName);
g.Wi("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){p9("onSessionChange: "+g.ai(a));
a||g.Yi("yt-remote-cast-receiver");G9("yt-remote-cast2-session-change",a)}),g.ka("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
p9("cloudview.createSingleton_: "+b);return b},zra=function(){var a=0<=g.ec.search(/\ (CrMo|Chrome|CriOS)\//);
return g.qi||a},b$=function(a,b){A9()?r9().setConnectedScreenStatus(a,b):C9("setConnectedScreenStatus called before ready.")},Ara=function(){p9("clearCurrentReceiver");
g.Yi("yt-remote-cast-receiver")},Bra=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){qra();a({command:"cast.sender.init"});return}}if(window.chrome)if(qra(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.wz();55<=b?a="55":50<=b&&(a="50");g.Dz("//www.gstatic.com/eureka/clank"+a+g.Bz,g.Az)}else g.Ez(0);else g.Az()},Cra=function(a){a?(g.Wi("yt-remote-session-app",a.app),g.Wi("yt-remote-session-name",a.name)):(g.Yi("yt-remote-session-app"),g.Yi("yt-remote-session-name"));
g.ka("yt.mdx.remote.channelParams_",a,void 0)},Dra=function(){var a=I9();
if(g.Tb(a)){var a=g.$i(),b=g.Xi("yt-remote-session-name")||"",c=g.Xi("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ka("yt.mdx.remote.channelParams_",a,void 0)}},Era=function(){var a=P9();
a?(Q9("Resume connection to: "+g.ai(a)),O9(a,0)):(g.jj(),Ara(),Q9("Skipping connecting because no session screen found."))},Fra=function(a){Q9("remote.onCastSessionChange_: "+g.ai(a));
if(a){var b=M9();b&&b.id==a.id?b$(b.id,"YouTube TV"):(b&&S9(),O9(a,1))}else t9()&&S9()},Gra=function(){var a=tra(),b=M9();
b||(b=P9());return g.Xa(a,function(a){return b&&g.Yh(b,a.key)?!0:!1})},Hra=function(){var a=g.Xi("yt-remote-cast-receiver");
return a?a.friendlyName:null},Ira=function(a,b,c,d){zra()?yra(b)&&(z9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?ora(a,c):(window.__onGCastApiAvailable=function(b,d){b?ora(a,c):(C9("Failed to load cast API: "+d),B9(!1),z9(!1),g.Yi("yt-remote-cast-available"),g.Yi("yt-remote-cast-receiver"),F9(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):rra():Bra())):p9("Cannot initialize because not running Chrome")},
Jra=function(a){this.B=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Of(a)||"";b&&(this.B=":"+b);this.A=g.Nf(a)||"";a=g.ec;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Na(a,"10.0")&&(this.o=!1))},c$=function(a,b,c){g.L.call(this);
this.H=a;this.Z=b;b.addEventListener("onVolumeChange",this.Jk,this);b.addEventListener("onCaptionsTrackListChanged",this.vu,this);b.addEventListener("captionschanged",this.ju,this);b.addEventListener("captionssettingschanged",this.Ko,this);b.addEventListener("videoplayerreset",this.Ki,this);b.addEventListener("mdxautoplaycancel",this.sr,this);this.C=!1;this.g=c;c.isDisposed();c.subscribe("proxyStateChange",this.Iu,this);c.subscribe("remotePlayerChange",this.Ji,this);c.subscribe("remoteQueueChange",
this.Ki,this);c.subscribe("autoplayUpNext",this.hu,this);c.subscribe("previousNextChange",this.Fu,this);c.subscribe("nowAutoplaying",this.yu,this);c.subscribe("autoplayDismissed",this.gu,this);this.suggestion=null;this.D=new g.ll(64);this.o=new g.Id(this.Mv,500,this);g.M(this,this.o);this.A=new g.Id(this.Nv,1E3,this);g.M(this,this.A);this.B={};this.G=new g.Id(this.Wv,1E3,this);g.M(this,this.G);this.F=new g.Sr(this.IL,1E3,this);g.M(this,this.F);this.J=g.w;this.Ko();this.Ki();this.Ji()},d$=function(a,
b){var c=a.H,d=a.Z.getVideoData().lengthSeconds;
c.H=b||0;c.g.Qa("progresssync",b,d)},Kra=function(a){d$(a,0);
a.o.stop();e$(a,new g.ll(64))},h$=function(a,b){if(f$(a)&&!a.C){var c=null;
b&&(c={style:a.Z.jj()},g.Zb(c,b));a.g.Gv(g$(a),c);a.B=V9(a.g).o}},i$=function(a,b){var c=a.Z.ne();
c?vra(a.g,g$(a),b,c.g,c.listId.toString()):vra(a.g,g$(a),b);e$(a,new g.ll(1))},Lra=function(a,b){if(b){var c=a.Z.Ec("captions","tracklist",{Ft:1});
c&&c.length?(a.Z.Ze("captions","track",b),a.C=!1):(a.Z.rp("captions"),a.C=!0)}else a.Z.Ze("captions","track",{})},f$=function(a){return V9(a.g).videoId==g$(a)},g$=function(a){return a.Z.getVideoData().videoId},e$=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.T(b,2);if(d!=g.T(a.D,2)){var e=a.Z;(e=g.Ol(e.app,e.playerType||1))&&g.NX(e,d)}a.D=b;Mra(a.H,c,b)}},j$=function(){var a=Gra();
!a&&D9()&&Hra()&&(a={key:"cast-selector-receiver",name:Hra()});return a},Nra=function(){var a=tra();
D9()&&g.Xi("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Ora=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.Ui&&jra();g.cj();N9||(N9=new Jra,g.lj()&&(N9.g="/api/loungedev"));J9||(J9=g.u("yt.mdx.remote.deferredProxies_")||[],g.ka("yt.mdx.remote.deferredProxies_",J9,void 0));Dra();var c=y9();if(!c){var d=new g.$z(N9);g.ka("yt.mdx.remote.screenService_",d,void 0);c=y9();Ira(a,d,function(a){a?w9()&&b$(w9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){G9("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.ka("yt.mdx.remote.initialized_",!0,void 0),Q9("Initializing: "+g.mf(b)),k$.push(g.zi("yt-remote-cast2-availability-change",function(){G9("yt-remote-receiver-availability-change")})),k$.push(g.zi("yt-remote-cast2-receiver-selected",function(){u9(null);
G9("yt-remote-auto-connect","cast-selector-receiver")})),k$.push(g.zi("yt-remote-cast2-receiver-resumed",function(){G9("yt-remote-receiver-resumed","cast-selector-receiver")})),k$.push(g.zi("yt-remote-cast2-session-change",Fra)),k$.push(g.zi("yt-remote-connection-change",function(a){a?b$(w9(),"YouTube TV"):P9()||(b$(null,null),Ara())})),a=I9(),b.isAuto&&(a.id+="#dial"),g.Fm("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,Q9(" -- with channel params: "+g.mf(a)),Cra(a),
c.start(),w9()||Era())},l$=function(){D9()?r9()?A9()?(p9("Requesting cast selector."),r9().requestSession()):(p9("Wait for cast API to be ready to request the session."),E9.push(g.zi("yt-remote-cast2-api-ready",l$))):C9("requestCastSelector: Cast is not initialized."):C9("requestCastSelector: Cast API is not installed!")},m$=function(a){g.iz.call(this,a);
this.A={key:g.ci(),name:g.Q("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.ll(64);this.H=0},Mra=function(a,b,c){a.F=c;
a.g.Qa("presentingplayerstatechange",new g.iC(c,b))},n$=function(a,b,c){if(b.key!=a.B.key)if(b.key==a.A.key)S9();
else{a.B=b;var d;if(!c){c=a.g.ne();d=a.g.getVideoData().videoId;var e;if(c){e=[];for(var f=0;f<c.B;f++)e[f]=c.Pb(f).videoId}else e=[a.g.getVideoData().videoId];d={videoIds:e,listId:a.g.Xe(),videoId:d,index:Math.max(a.g.Bw(),0),currentTime:a.g.getCurrentTime()}}a=d;Q9("Connecting to: "+g.mf(b));"cast-selector-receiver"==b.key?(u9(a||null),b=a||null,A9()?r9().setLaunchParams(b):C9("setLaunchParams called before ready.")):!a&&R9()&&w9()==b.key?G9("yt-remote-connection-change",!0):(S9(),u9(a||null),a=
y9().wd(),(b=g.ei(a,b.key))&&O9(b,1))}};
g.C(o9,g.Nz);g.h=o9.prototype;g.h.wd=function(a){return this.Jc.$_gs(a)};
g.h.contains=function(a){return!!this.Jc.$_c(a)};
g.h.get=function(a){return this.Jc.$_g(a)};
g.h.start=function(){this.Jc.$_st()};
g.h.Cl=function(a,b,c){this.Jc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Jc.$_r(a,b,c)};
g.h.ql=function(a,b,c,d){this.Jc.$_un(a,b,c,d)};
g.h.R=function(){for(var a=0,b=this.o.length;a<b;++a)this.Jc.$_ubk(this.o[a]);this.o.length=0;this.Jc=null;o9.M.R.call(this)};
g.h.EJ=function(){this.aa("screenChange")};
g.h.pG=function(){this.aa("onlineScreenChange")};
var x9=null,E9=[],J9=null,N9=null;g.C(U9,g.Hn);g.h=U9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.w,a$(this,"play")):W9(this,"play"),Z9(this,1,g.VB(V9(this))),this.aa("remotePlayerChange")):Y9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.w,a$(this,"pause")):W9(this,"pause"),Z9(this,2,g.VB(V9(this))),this.aa("remotePlayerChange")):Y9(this,this.pause)};
g.h.ow=function(a){if(1==this.g){if(this.o){var b=V9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.gb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.w,a$(this,"seekTo",{newTime:a}))}else W9(this,"seekTo",{newTime:a});Z9(this,3,a);this.aa("remotePlayerChange")}else Y9(this,g.B(this.ow,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.w,a$(this,"stopVideo")):W9(this,"stopVideo");var a=V9(this);a.index=-1;a.videoId="";g.TB(a);X9(this,a);this.aa("remotePlayerChange")}else Y9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=V9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){$9("set receiver volume: "+d)},this),(0,g.z)(function(){this.Qb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){$9("set receiver muted: "+b)},this),(0,g.z)(function(){this.Qb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);W9(this,"setVolume",e)}c.muted=b;c.volume=a;X9(this,c)}else Y9(this,g.B(this.setVolume,a,b))};
g.h.Gv=function(a,b){if(1==this.g){var c=V9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.mf(b.style),g.Zb(d,c.o));W9(this,"setSubtitlesTrack",d);X9(this,c)}else Y9(this,g.B(this.Gv,a,b))};
g.h.lp=function(a,b){if(1==this.g){W9(this,"setAudioTrack",{videoId:a,audioTrackId:b.zc.id});var c=V9(this);c.audioTrackId=b.zc.id;X9(this,c)}else Y9(this,g.B(this.lp,a,b))};
g.h.mw=function(a,b){if(1==this.g){if(a&&b){var c=V9(this);g.WB(c,a,b);X9(this,c)}W9(this,"previous")}else Y9(this,g.B(this.mw,a,b))};
g.h.lw=function(a,b){if(1==this.g){if(a&&b){var c=V9(this);g.WB(c,a,b);X9(this,c)}W9(this,"next")}else Y9(this,g.B(this.lw,a,b))};
g.h.Ur=function(){1==this.g?W9(this,"dismissAutoplay"):Y9(this,this.Ur)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.aa("proxyStateChange",a,this.g)}U9.M.dispose.call(this)};
g.h.R=function(){wra(this);this.B=null;this.C.clear();T9(this,null);U9.M.R.call(this)};
g.h.mp=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.aa("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.QB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.JG=function(a,b){this.aa(a,b)};
g.h.JE=function(a){if(!a)this.Hi(null),T9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=V9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)$9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,X9(this,b)}};
g.h.Hi=function(a){$9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),xra(this),this.aa("remotePlayerChange")};
g.h.IE=function(a){a?(xra(this),this.aa("remotePlayerChange")):this.Hi(null)};
g.h.SE=function(){var a=pra();a&&T9(this,a)};
g.h.Qb=function(a){g.Jz("CP",a)};
var k$=[];g.h=Jra.prototype;g.h.lg=function(a,b,c){var d=this.g;if(g.p(c)?c:this.o)d="https://"+this.A+this.B+this.g;return g.Wf(d+a,b||{})};
g.h.kp=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Db:g.B(this.zJ,c,!0),onError:g.B(this.yJ,d),Uc:g.B(this.AJ,d)};b&&(c.Sb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Gi(a,c)};
g.h.zJ=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.yJ=function(a,b){a(Error("Request error: "+b.status))};
g.h.AJ=function(a){a(Error("request timed out"))};
g.C(c$,g.L);g.h=c$.prototype;
g.h.R=function(){c$.M.R.call(this);this.o.stop();this.A.stop();this.J();this.Z.removeEventListener("onVolumeChange",this.Jk,this);this.Z.removeEventListener("onCaptionsTrackListChanged",this.vu,this);this.Z.removeEventListener("captionschanged",this.ju,this);this.Z.removeEventListener("videoplayerreset",this.Ki,this);this.Z.removeEventListener("captionssettingschanged",this.Ko,this);this.Z.removeEventListener("mdxautoplaycancel",this.sr,this);this.g.Ja("proxyStateChange",this.Iu,this);this.g.Ja("remotePlayerChange",
this.Ji,this);this.g.Ja("remoteQueueChange",this.Ki,this);this.g.Ja("autoplayUpNext",this.hu,this);this.g.Ja("previousNextChange",this.Fu,this);this.g.Ja("nowAutoplaying",this.yu,this);this.g.Ja("autoplayDismissed",this.gu,this);this.g=this.H=null};
g.h.ix=function(a,b){2==this.g.g||(f$(this)?this.gC.apply(this,arguments):this.dC.apply(this,arguments))};
g.h.ju=function(a){this.ix("control_subtitles_set_track",g.Tb(a)?null:a)};
g.h.Ko=function(){var a=this.Z.Ec("captions","track");g.Tb(a)||h$(this,a)};
g.h.dC=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":i$(this,this.Z.getCurrentTime());break;case "control_seek":i$(this,c[0]);break;case "control_subtitles_set_track":h$(this,c[0]);break;case "control_set_audio_track":c=c[0],f$(this)&&this.g.lp(g$(this),c)}};
g.h.gC=function(a,b){if(1081!=V9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":V9(this.g).gb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Ug(c[0],c[1]);break;case "control_subtitles_set_track":h$(this,c[0]);break;case "control_set_audio_track":c=c[0],f$(this)&&this.g.lp(g$(this),c)}}};
g.h.Jk=function(a){if(f$(this)){this.g.Ja("remotePlayerChange",this.Ji,this);var b=Math.round(a.volume);a=!!a.muted;var c=V9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Ji,this)}};
g.h.vu=function(){g.Tb(this.B)||Lra(this,this.B);this.C=!1};
g.h.Iu=function(a,b){this.A.stop();2==b&&this.Nv()};
g.h.Ji=function(){if(f$(this)){this.o.stop();var a=V9(this.g);switch(a.g){case 1081:e$(this,new g.ll(8));break;case 1:this.Mv();e$(this,new g.ll(8));break;case 1083:case 3:e$(this,new g.ll(9));break;case 0:e$(this,new g.ll(2));this.F.stop();d$(this,this.Z.getVideoData().lengthSeconds);break;case 1082:e$(this,new g.ll(4));break;case 2:e$(this,new g.ll(4));d$(this,g.VB(a));break;case -1:e$(this,new g.ll(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.Q("YTP_MDX_PLAYER_ERROR")},e$(this,
new g.ll(128,a))}var a=V9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,Lra(this,a));a=V9(this.g);-1==a.volume||Math.round(this.Z.getVolume())==a.volume&&this.Z.Bd()==a.muted||this.G.isActive()||this.Wv()}else Kra(this)};
g.h.Fu=function(){this.Z.Qa("mdxpreviousnextchange")};
g.h.Ki=function(){f$(this)||Kra(this)};
g.h.sr=function(){this.g.Ur()};
g.h.hu=function(a){a&&(a=g.Gi("/watch_queue_ajax",{method:"GET",Cc:{action_get_watch_queue_item:1,video_id:a},Db:(0,g.z)(this.DH,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.DH=function(a,b){var c=new g.By({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.Z.Qa("mdxautoplayupnext",c)};
g.h.yu=function(a){(0,window.isNaN)(a)||this.Z.Qa("mdxnowautoplaying",a)};
g.h.gu=function(){this.Z.Qa("mdxautoplaycanceled")};
g.h.IL=function(a,b){-1==V9(this.g).g?i$(this,a):b&&this.g.ow(a)};
g.h.Wv=function(){if(f$(this)){var a=V9(this.g);this.Z.removeEventListener("onVolumeChange",this.Jk,this);a.muted?this.Z.mute():this.Z.rf();this.Z.setVolume(a.volume);this.Z.addEventListener("onVolumeChange",this.Jk,this)}};
g.h.Mv=function(){this.o.stop();if(!this.g.isDisposed()){var a=V9(this.g);a.gb()&&e$(this,new g.ll(8));d$(this,g.VB(a));this.o.start()}};
g.h.Nv=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.C(m$,g.iz);g.h=m$.prototype;g.h.create=function(){Ora("embedded"==g.V(this.g).g);this.D.push(g.zi("yt-remote-before-disconnect",this.FE,this));this.D.push(g.zi("yt-remote-connection-change",this.RG,this));this.D.push(g.zi("yt-remote-receiver-availability-change",this.Gu,this));this.D.push(g.zi("yt-remote-auto-connect",this.PG,this));this.D.push(g.zi("yt-remote-receiver-resumed",this.OG,this));this.Gu()};
g.h.load=function(){this.g.Dm();m$.M.load.call(this);this.C=new c$(this,this.g,this.o);var a;a=(a=L9())?a.currentTime:0;var b=R9()?new U9(t9(),void 0):null;0==a&&b&&(a=g.VB(V9(b)));0!=a&&(this.H=a||0,this.g.Qa("progresssync",a,void 0));Mra(this,this.F,this.F);g.j5(this.g.app,6)};
g.h.unload=function(){this.g.Qa("mdxautoplaycanceled");this.B=this.A;g.Db(this.C,this.o);this.o=this.C=null;m$.M.unload.call(this);g.j5(this.g.app,5)};
g.h.R=function(){g.Ai(this.D);m$.M.R.call(this)};
g.h.lj=function(a,b){this.loaded&&this.C.ix.apply(this.C,arguments)};
g.h.JB=function(){return this.loaded?this.C.suggestion:null};
g.h.Zw=function(){return this.o?V9(this.o).L:!1};
g.h.hasNext=function(){return this.o?V9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.iL=function(){var a=V9(this.o),b=this.g.getVideoData(),c=g.hm(this.g),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.G)()-a.A)/1E3:a.B;var l=1>=n9(a)-this.getCurrentTime(),m=a.J,n=n9(a),a=0<a.C?a.C+((0,g.G)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.jL=function(){this.o&&this.o.lw()};
g.h.kL=function(){this.o&&this.o.mw()};
g.h.FE=function(a){1==a&&(this.J=this.o?V9(this.o):null)};
g.h.RG=function(){var a=R9()?new U9(t9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Cb(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Fc(g.VB(a)));this.g.Qa("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.Gu=function(){this.G=[this.A].concat(Nra());var a=j$()||this.A;n$(this,a,!this.loaded);this.g.ya("onMdxReceiversChange")};
g.h.PG=function(){var a=j$();n$(this,a)};
g.h.OG=function(){this.B=j$()};
g.h.hL=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l$():n$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&l$(),!0):!1}};
g.h.lL=function(){W9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ue=function(){return!1};
window._exportCheck==g.xa&&g.ka("ytmod.player.remote",m$,void 0);})(_yt_player);
